Changed to generate instruction files.

diff --git a/tools/dist b/tools/dist
--- a/tools/dist
+++ b/tools/dist
@@ -1,5 +1,10 @@
 #!/bin/sh
 
+print_done()
+{
+  echo "done"
+}
+
 yog="src/yog-copying"
 
 archive="${1}"
@@ -8,50 +13,60 @@ if [ -z "${archive}" ]; then
   exit 1
 fi
 
-dir=$$
+dir="$$"
+archive_dir="${dir}/${archive}"
 
-echo "Extract source tree..."
+echo -n "Extract source tree..."
 mkdir "${dir}"
 if [ $? != 0 ]; then
   echo "can't make temporary directory"
   exit 2
 fi
-git archive "--prefix=${dir}/${archive}/" HEAD | tar xf -
+git archive "--prefix=${archive_dir}/" HEAD | tar xf -
 if [ $? != 0 ]; then
   echo "can't extract source tree"
   exit 2
 fi
+print_done
 
-echo "Generate configure etc..."
-(cd "${dir}/${archive}" && aclocal && autoheader && autoconf && automake)
+echo -n "Generate configure etc..."
+(cd "${archive_dir}" && aclocal && autoheader && autoconf && automake)
 if [ $? != 0 ]; then
   echo "can't generate configure etc."
   exit 2
 fi
-rm -rf "${dir}/${archive}/autom4te.cache"
+rm -rf "${archive_dir}/autom4te.cache"
 if [ $? != 0 ]; then
   echo "can't remove autom4te"
   exit 2
 fi
-grep -o "./miniyog\$(EXEEXT) yg2inc.yg [[:alnum:]_]\+.yg \$@" "${dir}/${archive}/src/Makefile.am.tmpl" | while read line
+srcdir="${archive_dir}/src"
+grep -o "./miniyog\$(EXEEXT) yg2inc.yg [[:alnum:]_]\+.yg \$@" "${srcdir}/Makefile.am.tmpl" | while read line
 do
   yg=`echo "${line}" | cut -d " " -f 2`
   src=`echo "${line}" | cut -d " " -f 3`
   dst="`echo "${src}" | cut -d "." -f 1`.inc"
-  ${yog} "${dir}/${archive}/src/${yg}" "${dir}/${archive}/src/${src}" "${dir}/${archive}/src/${dst}"
+  ${yog} "${srcdir}/${yg}" "${srcdir}/${src}" "${srcdir}/${dst}"
 done
+python2.6 "${archive_dir}/tools/inst.py" "${srcdir}/insts.def" "${archive_dir}"
+if [ $? != 0 ]; then
+  echo "can't generate instruction files."
+  exit 2
+fi
+print_done
 
-echo "Generate HTML document..."
-(cd "${dir}/${archive}/doc" && make)
+echo -n "Generate HTML document..."
+(cd "${archive_dir}/doc" && make)
 if [ $? != 0 ]; then
   echo "can't generate document"
   exit 2
 fi
-rm -rf "${dir}/${archive}/doc/_build" "${dir}/${archive}/doc/_static"
+rm -rf "${archive_dir}/doc/_build" "${archive_dir}/doc/_static"
 if [ $? != 0 ]; then
   echo "can't remove intermediate files for document"
   exit 2
 fi
+print_done
 
 echo -n "Archive .tar.gz..."
 (cd "${dir}" && tar czf "../${archive}.tar.gz" "${archive}")
@@ -59,28 +74,28 @@ if [ $? != 0 ]; then
   echo "can't archive .tar.gz"
   exit 2
 fi
-echo "done"
+print_done
 echo -n "Archive .tar.bz2..."
 (cd "${dir}" && tar cjf "../${archive}.tar.bz2" "${archive}")
 if [ $? != 0 ]; then
   echo "can't archive .tar.bz2"
   exit 2
 fi
-echo "done"
+print_done
 echo -n "Archive .tar.xz..."
 (cd "${dir}" && tar c "${archive}" | xz --compress > "../${archive}.tar.xz")
 if [ $? != 0 ]; then
   echo "can't archive .tar.xz"
   exit 2
 fi
-echo "done"
+print_done
 echo -n "Archive .zip..."
 (cd "${dir}" && zip -qr "../${archive}.zip" "${archive}")
 if [ $? != 0 ]; then
   echo "can't archive .zip"
   exit 2
 fi
-echo "done"
+print_done
 
 rm -rf "${dir}"
 if [ $? != 0 ]; then
